### PR TITLE
Update azure-waf-bypass.yaml

### PR DESCRIPTION
**Pull request by justmorpheus**

### CODE REVIEW

**Comment by korniko98** [comment]
Hi, why did you close the PR?

**Comment by justmorpheus** [comment]
My apologies, I was making some change and it got closed unintentionally.

let me reopen it.
Thanks

**Comment by korniko98** [comment]
Could you please add public references showing that Azure WAF in particular was vulnerable to command injection bypass using globbing patterns, and that this issue was fixed on July 16th, 2021?

**Comment by justmorpheus** [comment]
@korniko98 
So I reported this issue last year to Azure on 24 Jun 2021, 02:50.
image


You can see the payload and snapshot with fix status.

I am not getting time to update the blog hence there is no reference. Let me know if this snapshot works? 

Thanks

**Comment by korniko98** [comment]
I think it's important that we link to some public url as reference, maybe you could publish a short summary of your azure portal submission on twitter / github / linkedin and add a link to the tweet? or add a short note to the blogpost? and then after the item is added to the database, if you find the time to update your blog with more information you could add that as another reference as well.

**Comment by justmorpheus** [comment]
@korniko98, thanks for great suggestion.
 I have published a short summary with screenshot on twitter: https://twitter.com/justm0rph3u5/status/1542943538857799680

As well as on Linkedin: https://www.linkedin.com/feed/update/urn:li:activity:6948709212621266944/

I will update the blog over the weekend.

Thanks

**Pull request merged**
