### PR TITLE
Submission for AWS-CodeBuild-ECR-Vulnerability 

### PR DESCRIPTION
**Pull request by willdeane**

### CODE REVIEW

**Comment by 0xdabbad00** [comment]
I don't understand the risk presented from this. It seems someone with code execution within a container can replace their container image with one that gives them code execution within the container.  That sounds like they haven't gained anything.  Can you provide a scenario in which this would benefit the attacker such that what they ended up with by using this issue is more than what they started with?

**Comment by willdeane** [comment]
The issue is more about persistence within the pipeline rather than just getting code exec within the build containers. I think the most likely scenario is where the same image is used within multiple pipelines, an attacker with access to one build job/pipeline could compromise the image to gain access to other jobs/pipelines and the artifacts /creds etc associated with them.

**Comment by 0xdabbad00** [comment]
So to better understand it, it sounds like one possible scenario is maybe a developer has their laptop compromised, and that developer has access to project Foo at a company, but not the more sensitive Bar project.  The attacker submits a PR to project Foo using the developer's access which automatically has a code pipeline run for some unit tests.  When that runs, the attacker's code ends up executing which abuses this flaw, and let's the modify the image that the code pipeline is running on. This image is also used by project Bar.  So the next time a code pipeline is run for project Bar, the attacker's code is now run for the pipelines in that environment, which then get's pushed to prod there or has some secrets used in the pipeline that the attacker's code steals. Is that a scenario that would play out with this?

**Comment by willdeane** [comment]
Yes, this is definitely one scenario for this issue. Another is if temporary creds are leaked, e.g., to logs or build artifacts. Whilst there is some built in protection to mask STS creds in CloudTrail, a job that’s accidentally logging them to other systems or the output of `aws ecr get-login-password` to a log and/or artifact could provide another path to overwrite the build image and then get attacker-controlled code running within all impacted pipeline jobs.  It’s also been reported to me that there are a number of orgs using CodeBuild for things other than standard CI/CD. If these contained vulns, such as SSRF, that could be used to read the metadata service then again an attacker could replace the images for those services with the attacker-controlled code running the next time the job is run.

**Pull request merged**
